services:
  kafka_consumer:
    build: ./consumer
    container_name: kafka_consumer
    restart: "always"
    depends_on:
      kafka:
        condition: service_healthy 
      db:
        condition: service_healthy        
    networks:
      - kafka_network
    environment:
      BOOTSTRAP_SERVERS: kafka:9093
    secrets:
      - db-password
    volumes:
      - ./data:/app/data
  kafka:
    image: apache/kafka:4.1.0-rc1
    container_name: kafka
    ports:
      - "9092:9092"   # outside Docker (host access)
      - "9093:9093"   # inside Docker network
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://:9093,PLAINTEXT_EXTERNAL://:9092,CONTROLLER://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9093,PLAINTEXT_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    healthcheck:      
      test: ["CMD", "bash", "-c", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9093 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - kafka_network     
    volumes:
      - kafka-data:/var/lib/kafka/data

  db:
      image: postgres
      container_name: postgres-db
      restart: always
      user: postgres
      secrets:
        - db-password
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=openFoam
        - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      expose:
        - 5432
      ports:
        - "5432:5432"
      networks:
        - kafka_network             
      healthcheck:
        test: ["CMD", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5

  backend:
    container_name: backend
    build:
      context: ./api
    ports:
      - 8001:8001
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=openFoam
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    networks:
      - kafka_network
    develop:
      watch:
        - action: rebuild
          path: .    
volumes:
  db-data:  
  kafka-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  kafka_network:
    driver: bridge